version: "3.3"


services:
  app:
    build: .
    volumes:
      - ./:/home/zagum/Hillel/code
    env_file: .env
    expose:
      - 8000
  ngnix:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - app
