version: "3.3"


services:
  app:
    build: .
    env_file: .env
    expose:
      - 8000
  ngnix:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
